<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MemoryLog.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MailKit" Version="4.17.0">
      <GeneratePathProperty>True</GeneratePathProperty>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\bluepen.powershell.domain\bluepen.powershell.domain.csproj" />
  </ItemGroup>

</Project>
